"""
02_make_sft_policy_data.py
Build SFT training data for Prompt Policy from BasePack-v2 files.

Data composition (per the revised design):
  ~70% LLM-rewritten hints generated by Qwen3-8B under 6 different system prompts
  ~30% template hints as format anchors

The 6 system-prompt emphases:
  verifiability, narrative_manipulation, stance_conflict,
  source_grounding, temporal_anomaly, neutral_synthesis

Output is LLaMA-Factory alpaca format.

Input:  basepack_v2/basepack_{train,val}.jsonl
Output: policy_data/sft/{train,val}.json
"""

import json
import re
import random
import argparse
from pathlib import Path

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

INSTRUCTION = (
    "Generate a concise focus_hint for LLM-assisted rumor analysis. "
    "Return only a JSON object with the key focus_hint."
)

TEMPLATE_HINTS = {
    "balanced_focus": (
        "Summarize the central claim, compare supportive and skeptical replies, "
        "check source grounding, and note whether the evidence is concrete or mainly emotional."
    ),
    "query_focus": (
        "Prioritize questioning replies and uncertainty signals. Check what details are missing "
        "from the source claim, especially time, location, actor, source attribution, and evidence form."
    ),
    "deny_focus": (
        "Prioritize replies that deny, correct, or challenge the source claim. Compare them with "
        "supportive replies and identify whether the disagreement is based on evidence or speculation."
    ),
    "source_grounding_focus": (
        "Focus on whether the source post contains verifiable information such as named entities, "
        "time, location, source links, or attribution. Be cautious if the claim is vague."
    ),
}

LLM_SYSTEM_PROMPTS = {
    "verifiability": (
        "You are a rumor analysis expert. Generate a focus hint emphasizing verifiability: "
        "whether the claim can be checked against external facts, named entities, timestamps, "
        "source attribution, or official records. Be concrete and specific to this event."
    ),
    "narrative_manipulation": (
        "You are a rumor analysis expert. Generate a focus hint emphasizing narrative manipulation: "
        "emotional appeals, exaggeration, missing context, one-sided framing, or persuasion techniques "
        "in the source post and supporting replies. Be concrete and specific to this event."
    ),
    "stance_conflict": (
        "You are a rumor analysis expert. Generate a focus hint emphasizing stance conflict: "
        "the distribution of agreement, denial, and doubt in the replies, and what this pattern "
        "reveals about the claim's credibility. Be concrete and specific to this event."
    ),
    "source_grounding": (
        "You are a rumor analysis expert. Generate a focus hint emphasizing source grounding: "
        "whether the claim is anchored to a credible source, institutional authority, or direct evidence, "
        "or whether it floats without attribution. Be concrete and specific to this event."
    ),
    "temporal_anomaly": (
        "You are a rumor analysis expert. Generate a focus hint emphasizing temporal signals: "
        "timing anomalies, recirculated old content, temporal inconsistencies, or whether the claim "
        "matches the propagation timeline. Be concrete and specific to this event."
    ),
    "neutral_synthesis": (
        "You are a rumor analysis expert. Generate a balanced, neutral focus hint that synthesizes "
        "all available signals without presuming the claim is true or fake. Identify the key uncertainty "
        "and what a downstream model should pay most attention to."
    ),
}

JSON_RE = re.compile(r'\{[^{}]*"focus_hint"\s*:\s*"([^"]+)"[^{}]*\}', re.DOTALL)

DENY_KEYWORDS = re.compile(
    r"\b(fake|false|hoax|not true|debunked|wrong|incorrect|lie|liar|fabricated|misinformation)\b",
    re.IGNORECASE,
)
ENTITY_PATTERN = re.compile(
    r"\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*|[A-Z]{2,}|\d{4}[-/]\d{2}[-/]\d{2})\b"
)


def select_template_hint(event: dict) -> str:
    replies = event.get("selected_replies", [])
    if isinstance(replies[0], dict) if replies else False:
        reply_texts = [r["text"] for r in replies]
    else:
        reply_texts = replies
    source_text = event.get("source_text", "")
    stats = event.get("stats", {})
    reply_text = " ".join(reply_texts)

    if DENY_KEYWORDS.search(reply_text):
        return TEMPLATE_HINTS["deny_focus"]
    if reply_text.count("?") >= 3:
        return TEMPLATE_HINTS["query_focus"]
    entities = ENTITY_PATTERN.findall(source_text)
    if len(source_text.split()) < 20 or len(entities) < 2:
        return TEMPLATE_HINTS["source_grounding_focus"]
    return TEMPLATE_HINTS["balanced_focus"]


def build_policy_input(event: dict) -> str:
    source_text = event.get("source_text", "")
    replies = event.get("selected_replies", [])

    lines = ["SOURCE:", source_text, "", "REPLIES:"]
    for i, r in enumerate(replies, 1):
        text = r["text"] if isinstance(r, dict) else r
        lines.append(f"{i}. {text}")

    stats = event.get("stats", {})
    stance_dist = event.get("stance_dist", {})
    lines.append("")
    lines.append(
        f"STATS:\nreply_count={stats.get('num_replies', 0)} | "
        f"depth={stats.get('max_depth', 0)} | "
        f"branches={stats.get('num_branches', 0)}"
    )
    if stance_dist:
        dist_str = " | ".join(f"{s}={stance_dist.get(s, 0.0)}" for s in ["support", "deny", "query", "neutral"])
        lines.append(f"STANCE_DIST: {dist_str}")
    return "\n".join(lines)


def load_llm(model_name: str):
    print(f"Loading LLM for hint generation: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        torch_dtype=torch.bfloat16,
        device_map="auto",
        trust_remote_code=True,
    )
    model.eval()
    return tokenizer, model


def generate_llm_hint(tokenizer, model, system_prompt: str,
                      event: dict, max_new_tokens: int = 120) -> str | None:
    policy_input = build_policy_input(event)
    user_msg = (
        f"{policy_input}\n\n"
        "Based on the event above, generate a focus_hint (30-80 words) for rumor analysis. "
        "Return only: {\"focus_hint\": \"...\"}"
    )
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_msg},
    ]
    text = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True, enable_thinking=False
    )
    inputs = tokenizer([text], return_tensors="pt").to(model.device)
    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            temperature=None,
            top_p=None,
            pad_token_id=tokenizer.pad_token_id,
        )
    generated = tokenizer.decode(
        output_ids[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True
    ).strip()

    m = JSON_RE.search(generated)
    if m:
        return m.group(1).strip()
    try:
        obj = json.loads(generated)
        if "focus_hint" in obj:
            return str(obj["focus_hint"]).strip()
    except json.JSONDecodeError:
        pass
    return None


def build_sft_sample(event_id: str, policy_input: str, hint_text: str) -> dict:
    return {
        "event_id": event_id,
        "instruction": INSTRUCTION,
        "input": policy_input,
        "output": json.dumps({"focus_hint": hint_text}, ensure_ascii=False),
    }


def process_split(input_path: Path, output_path: Path,
                  tokenizer, model, template_ratio: float = 0.3,
                  deduplicate: bool = True, resume: bool = True):
    output_path.parent.mkdir(parents=True, exist_ok=True)

    events = []
    with open(input_path) as f:
        for line in f:
            if line.strip():
                events.append(json.loads(line))

    print(f"  Loaded {len(events)} events from {input_path}")

    samples = []
    existing_event_ids: set[str] = set()
    existing_inputs: set[str] = set()
    # resume 模式：读取已有样本并仅补齐缺失 event
    if resume and output_path.exists():
        try:
            with open(output_path, "r", encoding="utf-8") as f:
                loaded = json.load(f)
            if isinstance(loaded, list):
                samples = loaded
                for item in loaded:
                    if isinstance(item, dict):
                        if isinstance(item.get("event_id"), str):
                            existing_event_ids.add(item["event_id"])
                        if isinstance(item.get("input"), str):
                            existing_inputs.add(item["input"])
                print(
                    f"  Resume enabled: found {len(samples)} existing samples, "
                    f"{len(existing_event_ids)} with event_id."
                )
        except Exception as e:
            print(f"  [WARN] Failed to load existing {output_path}: {e}. Rebuilding this split.")
            samples = []
            existing_event_ids = set()
            existing_inputs = set()

    pending_events = []
    for i, event in enumerate(events, 1):
        policy_input = build_policy_input(event)
        event_id = str(event.get("event_id", f"idx_{i-1}"))
        if resume and (event_id in existing_event_ids or policy_input in existing_inputs):
            continue
        pending_events.append((event_id, policy_input, event))

    print(f"  Pending generation: {len(pending_events)}/{len(events)}")

    generated_count = 0
    seen_hints: set = set()

    for i, (event_id, policy_input, event) in enumerate(pending_events, 1):

        use_template = (tokenizer is None) or (random.random() < template_ratio)

        if use_template:
            hint = select_template_hint(event)
            # 模板分支也必须保证每个 event 产出一条样本，不能因为全局去重而跳过
            if deduplicate:
                seen_hints.add(hint)
            samples.append(build_sft_sample(event_id, policy_input, hint))
        else:
            system_key = random.choice(list(LLM_SYSTEM_PROMPTS.keys()))
            system_prompt = LLM_SYSTEM_PROMPTS[system_key]
            hint = generate_llm_hint(tokenizer, model, system_prompt, event)
            if hint is None or (deduplicate and hint in seen_hints):
                hint = select_template_hint(event)
            if deduplicate:
                seen_hints.add(hint)
            samples.append(build_sft_sample(event_id, policy_input, hint))

        generated_count += 1

        if i % 100 == 0:
            print(f"    Progress: {i}/{len(pending_events)}")

    with open(output_path, "w") as f:
        json.dump(samples, f, ensure_ascii=False, indent=2)

    print(f"  -> {output_path}  ({len(samples)} samples, newly generated: {generated_count})")


def main():
    parser = argparse.ArgumentParser(description="Build SFT policy data (template + LLM mix)")
    parser.add_argument("--basepack_dir", default="basepack_v2",
                        help="Directory with basepack_v2 files")
    parser.add_argument("--output_dir", default="policy_data/sft")
    parser.add_argument("--splits", nargs="+", default=["train", "val"])
    parser.add_argument("--llm_model", default="Qwen/Qwen3-8B",
                        help="LLM for generating rewritten hints")
    parser.add_argument("--template_ratio", type=float, default=0.3,
                        help="Fraction of samples using template hints (rest use LLM)")
    parser.add_argument("--no_llm", action="store_true",
                        help="Skip LLM; use only template hints (for quick testing)")
    parser.add_argument("--cuda_devices", default=None,
                        help='Restrict visible GPUs, e.g. "4,5".')
    parser.add_argument("--no_resume", action="store_true",
                        help="Disable resume mode and rebuild split from scratch")
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    random.seed(args.seed)

    if args.cuda_devices:
        # 在加载模型前限制可见 GPU，避免 device_map=auto 均匀占满所有卡
        import os
        os.environ["CUDA_VISIBLE_DEVICES"] = args.cuda_devices
        print(f"CUDA_VISIBLE_DEVICES={args.cuda_devices}")

    tokenizer, model = None, None
    if not args.no_llm:
        tokenizer, model = load_llm(args.llm_model)

    basepack_dir = Path(args.basepack_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    for split in args.splits:
        input_path = basepack_dir / f"basepack_{split}.jsonl"
        if not input_path.exists():
            print(f"[WARN] Not found: {input_path}, skipping.")
            continue
        output_path = output_dir / f"{split}.json"
        print(f"\nBuilding SFT data for {split}...")
        process_split(input_path, output_path, tokenizer, model,
                      template_ratio=args.template_ratio, resume=not args.no_resume)

    print("\nSFT data build complete.")


if __name__ == "__main__":
    main()
